-- NYC Taxi Analytics Database Schema
-- This schema supports normalized storage of taxi trip data with zones

-- Create zones table for location data
CREATE TABLE IF NOT EXISTS zones (
    location_id INTEGER PRIMARY KEY,
    borough VARCHAR(50) NOT NULL,
    zone VARCHAR(100) NOT NULL,
    service_zone VARCHAR(50) NOT NULL
);

-- Create trips table for trip data
CREATE TABLE IF NOT EXISTS trips (
    id VARCHAR(36) PRIMARY KEY,
    
    -- Timestamps
    pickup_datetime TIMESTAMP NOT NULL,
    dropoff_datetime TIMESTAMP NOT NULL,
    
    -- Location data
    pickup_location_id INTEGER REFERENCES zones(location_id),
    dropoff_location_id INTEGER REFERENCES zones(location_id),
    pickup_longitude DECIMAL(10, 7) NOT NULL,
    pickup_latitude DECIMAL(10, 7) NOT NULL,
    dropoff_longitude DECIMAL(10, 7) NOT NULL,
    dropoff_latitude DECIMAL(10, 7) NOT NULL,
    
    -- Trip metrics
    passenger_count INTEGER NOT NULL DEFAULT 1,
    trip_distance DECIMAL(8, 2) NOT NULL, -- in miles
    trip_duration INTEGER NOT NULL, -- in seconds
    
    -- Fare information
    fare_amount DECIMAL(8, 2) NOT NULL,
    tip_amount DECIMAL(8, 2) NOT NULL DEFAULT 0.0,
    tolls_amount DECIMAL(8, 2) NOT NULL DEFAULT 0.0,
    total_amount DECIMAL(8, 2) NOT NULL,
    
    -- Payment information
    payment_type INTEGER NOT NULL, -- 1=Credit card, 2=Cash, etc.
    
    -- Derived features
    trip_speed_mph DECIMAL(8, 2), -- miles per hour
    fare_per_mile DECIMAL(8, 2),  -- fare amount per mile
    idle_time_minutes DECIMAL(8, 2), -- estimated idle time
    
    -- Metadata
    vendor_id VARCHAR(10),
    store_and_fwd_flag VARCHAR(1)
);

-- Create indexes for better query performance
CREATE INDEX IF NOT EXISTS idx_trips_pickup_datetime ON trips(pickup_datetime);
CREATE INDEX IF NOT EXISTS idx_trips_dropoff_datetime ON trips(dropoff_datetime);
CREATE INDEX IF NOT EXISTS idx_trips_pickup_location ON trips(pickup_location_id);
CREATE INDEX IF NOT EXISTS idx_trips_dropoff_location ON trips(dropoff_location_id);
CREATE INDEX IF NOT EXISTS idx_trips_fare_amount ON trips(fare_amount);
CREATE INDEX IF NOT EXISTS idx_trips_trip_distance ON trips(trip_distance);
CREATE INDEX IF NOT EXISTS idx_trips_payment_type ON trips(payment_type);
CREATE INDEX IF NOT EXISTS idx_trips_passenger_count ON trips(passenger_count);

-- Composite indexes for common queries
CREATE INDEX IF NOT EXISTS idx_trips_datetime_location ON trips(pickup_datetime, pickup_location_id);
CREATE INDEX IF NOT EXISTS idx_trips_fare_distance ON trips(fare_amount, trip_distance);
CREATE INDEX IF NOT EXISTS idx_trips_payment_fare ON trips(payment_type, fare_amount);

-- Indexes for zones
CREATE INDEX IF NOT EXISTS idx_zones_borough ON zones(borough);
CREATE INDEX IF NOT EXISTS idx_zones_zone ON zones(zone);

-- Create views for common analytics queries
CREATE OR REPLACE VIEW daily_trip_stats AS
SELECT 
    DATE(pickup_datetime) as trip_date,
    COUNT(*) as trip_count,
    AVG(fare_amount) as avg_fare,
    AVG(trip_distance) as avg_distance,
    AVG(trip_duration/60.0) as avg_duration_minutes,
    SUM(total_amount) as total_revenue,
    AVG(trip_speed_mph) as avg_speed
FROM trips
GROUP BY DATE(pickup_datetime)
ORDER BY trip_date;

CREATE OR REPLACE VIEW hourly_trip_patterns AS
SELECT 
    EXTRACT(hour FROM pickup_datetime) as hour_of_day,
    COUNT(*) as trip_count,
    AVG(fare_amount) as avg_fare,
    AVG(trip_distance) as avg_distance,
    AVG(trip_duration/60.0) as avg_duration_minutes
FROM trips
GROUP BY EXTRACT(hour FROM pickup_datetime)
ORDER BY hour_of_day;

CREATE OR REPLACE VIEW borough_analytics AS
SELECT 
    z.borough,
    COUNT(t.id) as trip_count,
    AVG(t.fare_amount) as avg_fare,
    AVG(t.trip_distance) as avg_distance,
    AVG(t.trip_duration/60.0) as avg_duration_minutes,
    SUM(t.total_amount) as total_revenue
FROM zones z
LEFT JOIN trips t ON z.location_id = t.pickup_location_id
GROUP BY z.borough
ORDER BY trip_count DESC;

-- Insert default taxi zones data (simplified version)
-- In a real implementation, you would load the full taxi zone lookup table
INSERT INTO zones (location_id, borough, zone, service_zone) VALUES
(1, 'EWR', 'Newark Airport', 'EWR'),
(2, 'Queens', 'Jamaica Bay', 'Boro Zone'),
(3, 'Bronx', 'Allerton/Pelham Gardens', 'Boro Zone'),
(4, 'Manhattan', 'Alphabet City', 'Yellow Zone'),
(5, 'Staten Island', 'Arden Heights', 'Boro Zone'),
(6, 'Staten Island', 'Arrochar/Fort Wadsworth', 'Boro Zone'),
(7, 'Queens', 'Astoria', 'Boro Zone'),
(8, 'Queens', 'Astoria Park', 'Boro Zone'),
(9, 'Queens', 'Auburndale', 'Boro Zone'),
(10, 'Queens', 'Baisley Park', 'Boro Zone'),
(11, 'Brooklyn', 'Bath Beach', 'Boro Zone'),
(12, 'Manhattan', 'Battery Park', 'Yellow Zone'),
(13, 'Manhattan', 'Battery Park City', 'Yellow Zone'),
(14, 'Brooklyn', 'Bay Ridge', 'Boro Zone'),
(15, 'Queens', 'Bay Terrace/Fort Totten', 'Boro Zone'),
(16, 'Queens', 'Bayside', 'Boro Zone'),
(17, 'Brooklyn', 'Bedford', 'Boro Zone'),
(18, 'Bronx', 'Bedford Park', 'Boro Zone'),
(19, 'Queens', 'Bellerose', 'Boro Zone'),
(20, 'Bronx', 'Belmont', 'Boro Zone'),
(21, 'Brooklyn', 'Bensonhurst East', 'Boro Zone'),
(22, 'Brooklyn', 'Bensonhurst West', 'Boro Zone'),
(23, 'Staten Island', 'Bloomfield/Emerson Hill', 'Boro Zone'),
(24, 'Manhattan', 'Bloomingdale', 'Yellow Zone'),
(25, 'Brooklyn', 'Boerum Hill', 'Boro Zone'),
(26, 'Brooklyn', 'Borough Park', 'Boro Zone'),
(27, 'Queens', 'Breezy Point/Fort Tilden/Riis Beach', 'Boro Zone'),
(28, 'Queens', 'Briarwood/Jamaica Hills', 'Boro Zone'),
(29, 'Brooklyn', 'Brighton Beach', 'Boro Zone'),
(30, 'Queens', 'Broad Channel', 'Boro Zone'),
(31, 'Bronx', 'Bronx Park', 'Boro Zone'),
(32, 'Bronx', 'Bronxdale', 'Boro Zone'),
(33, 'Brooklyn', 'Brooklyn Heights', 'Boro Zone'),
(34, 'Brooklyn', 'Brooklyn Navy Yard', 'Boro Zone'),
(35, 'Brooklyn', 'Brownsville', 'Boro Zone'),
(36, 'Brooklyn', 'Bushwick North', 'Boro Zone'),
(37, 'Brooklyn', 'Bushwick South', 'Boro Zone'),
(38, 'Queens', 'Cambria Heights', 'Boro Zone'),
(39, 'Brooklyn', 'Canarsie', 'Boro Zone'),
(40, 'Brooklyn', 'Carroll Gardens', 'Boro Zone'),
(41, 'Manhattan', 'Central Harlem', 'Yellow Zone'),
(42, 'Manhattan', 'Central Harlem North', 'Yellow Zone'),
(43, 'Manhattan', 'Central Park', 'Yellow Zone'),
(44, 'Staten Island', 'Charleston/Tottenville', 'Boro Zone'),
(45, 'Manhattan', 'Chinatown', 'Yellow Zone'),
(46, 'Bronx', 'City Island', 'Boro Zone'),
(47, 'Bronx', 'Claremont/Bathgate', 'Boro Zone'),
(48, 'Manhattan', 'Clinton East', 'Yellow Zone'),
(49, 'Brooklyn', 'Clinton Hill', 'Boro Zone'),
(50, 'Manhattan', 'Clinton West', 'Yellow Zone'),
(51, 'Brooklyn', 'Cobble Hill', 'Boro Zone'),
(52, 'Queens', 'College Point', 'Boro Zone'),
(53, 'Brooklyn', 'Columbia Street', 'Boro Zone'),
(54, 'Brooklyn', 'Coney Island', 'Boro Zone'),
(55, 'Queens', 'Corona', 'Boro Zone'),
(56, 'Queens', 'Corona', 'Boro Zone'),
(57, 'Bronx', 'Country Club', 'Boro Zone'),
(58, 'Bronx', 'Crotona Park', 'Boro Zone'),
(59, 'Bronx', 'Crotona Park East', 'Boro Zone'),
(60, 'Brooklyn', 'Crown Heights North', 'Boro Zone'),
(61, 'Brooklyn', 'Crown Heights South', 'Boro Zone'),
(62, 'Brooklyn', 'Cypress Hills', 'Boro Zone'),
(63, 'Queens', 'Douglaston', 'Boro Zone'),
(64, 'Brooklyn', 'Downtown Brooklyn/MetroTech', 'Boro Zone'),
(65, 'Brooklyn', 'DUMBO/Vinegar Hill', 'Boro Zone'),
(66, 'Brooklyn', 'Dyker Heights', 'Boro Zone'),
(67, 'Manhattan', 'East Chelsea', 'Yellow Zone'),
(68, 'Bronx', 'East Concourse/Concourse Village', 'Boro Zone'),
(69, 'Queens', 'East Elmhurst', 'Boro Zone'),
(70, 'Brooklyn', 'East Flatbush/Farragut', 'Boro Zone'),
(71, 'Brooklyn', 'East Flatbush/Remsen Village', 'Boro Zone'),
(72, 'Queens', 'East Flushing', 'Boro Zone'),
(73, 'Manhattan', 'East Harlem North', 'Yellow Zone'),
(74, 'Manhattan', 'East Harlem South', 'Yellow Zone'),
(75, 'Brooklyn', 'East New York', 'Boro Zone'),
(76, 'Brooklyn', 'East New York/Pennsylvania Ave', 'Boro Zone'),
(77, 'Bronx', 'East Tremont', 'Boro Zone'),
(78, 'Manhattan', 'East Village', 'Yellow Zone'),
(79, 'Queens', 'Eastchester', 'Boro Zone'),
(80, 'Bronx', 'Edenwald', 'Boro Zone'),
(81, 'Brooklyn', 'Flatbush/Ditmas Park', 'Boro Zone'),
(82, 'Manhattan', 'Flatiron', 'Yellow Zone'),
(83, 'Brooklyn', 'Flatlands', 'Boro Zone'),
(84, 'Queens', 'Flushing', 'Boro Zone'),
(85, 'Queens', 'Flushing Meadows-Corona Park', 'Boro Zone'),
(86, 'Queens', 'Forest Hills', 'Boro Zone'),
(87, 'Queens', 'Forest Park/Highland Park', 'Boro Zone'),
(88, 'Brooklyn', 'Fort Greene', 'Boro Zone'),
(89, 'Queens', 'Fresh Meadows', 'Boro Zone'),
(90, 'Staten Island', 'Freshkills Park', 'Boro Zone'),
(91, 'Manhattan', 'Garment District', 'Yellow Zone'),
(92, 'Queens', 'Glen Oaks', 'Boro Zone'),
(93, 'Queens', 'Glendale', 'Boro Zone'),
(94, 'Manhattan', 'Governors Island', 'Yellow Zone'),
(95, 'Brooklyn', 'Gowanus', 'Boro Zone'),
(96, 'Manhattan', 'Gramercy', 'Yellow Zone'),
(97, 'Brooklyn', 'Gravesend', 'Boro Zone'),
(98, 'Staten Island', 'Great Kills', 'Boro Zone'),
(99, 'Staten Island', 'Great Kills Park', 'Boro Zone'),
(100, 'Brooklyn', 'Green-Wood Cemetery', 'Boro Zone'),
(101, 'Brooklyn', 'Greenpoint', 'Boro Zone'),
(102, 'Manhattan', 'Greenwich Village North', 'Yellow Zone'),
(103, 'Manhattan', 'Greenwich Village South', 'Yellow Zone'),
(104, 'Staten Island', 'Grymes Hill/Clifton', 'Boro Zone'),
(105, 'Manhattan', 'Hamilton Heights', 'Yellow Zone'),
(106, 'Queens', 'Hammels/Arverne', 'Boro Zone'),
(107, 'Staten Island', 'Heartland Village/Todt Hill', 'Boro Zone'),
(108, 'Bronx', 'Highbridge', 'Boro Zone'),
(109, 'Manhattan', 'Highbridge Park', 'Yellow Zone'),
(110, 'Queens', 'Hillcrest/Pomonok', 'Boro Zone'),
(111, 'Queens', 'Hollis', 'Boro Zone'),
(112, 'Brooklyn', 'Homecrest', 'Boro Zone'),
(113, 'Queens', 'Howard Beach', 'Boro Zone'),
(114, 'Manhattan', 'Hudson Sq', 'Yellow Zone'),
(115, 'Bronx', 'Hunts Point', 'Boro Zone'),
(116, 'Manhattan', 'Inwood', 'Yellow Zone'),
(117, 'Manhattan', 'Inwood Hill Park', 'Yellow Zone'),
(118, 'Queens', 'Jackson Heights', 'Boro Zone'),
(119, 'Queens', 'Jamaica', 'Boro Zone'),
(120, 'Queens', 'Jamaica Estates', 'Boro Zone'),
(121, 'Queens', 'JFK Airport', 'Airports'),
(122, 'Brooklyn', 'Kensington', 'Boro Zone'),
(123, 'Queens', 'Kew Gardens', 'Boro Zone'),
(124, 'Queens', 'Kew Gardens Hills', 'Boro Zone'),
(125, 'Bronx', 'Kingsbridge', 'Boro Zone'),
(126, 'Bronx', 'Kingsbridge Heights', 'Boro Zone'),
(127, 'Brooklyn', 'Kings Highway', 'Boro Zone'),
(128, 'Queens', 'Kissena Park', 'Boro Zone'),
(129, 'Queens', 'LaGuardia Airport', 'Airports'),
(130, 'Queens', 'Laurelton', 'Boro Zone'),
(131, 'Manhattan', 'Lenox Hill East', 'Yellow Zone'),
(132, 'Manhattan', 'Lenox Hill West', 'Yellow Zone'),
(133, 'Manhattan', 'Lincoln Square East', 'Yellow Zone'),
(134, 'Manhattan', 'Lincoln Square West', 'Yellow Zone'),
(135, 'Manhattan', 'Little Italy/NoLiTa', 'Yellow Zone'),
(136, 'Queens', 'Long Island City/Hunters Point', 'Boro Zone'),
(137, 'Queens', 'Long Island City/Queens Plaza', 'Boro Zone'),
(138, 'Bronx', 'Longwood', 'Boro Zone'),
(139, 'Manhattan', 'Lower East Side', 'Yellow Zone'),
(140, 'Brooklyn', 'Madison', 'Boro Zone'),
(141, 'Brooklyn', 'Manhattan Beach', 'Boro Zone'),
(142, 'Manhattan', 'Manhattan Valley', 'Yellow Zone'),
(143, 'Manhattan', 'Manhattanville', 'Yellow Zone'),
(144, 'Manhattan', 'Marble Hill', 'Yellow Zone'),
(145, 'Brooklyn', 'Marine Park/Floyd Bennett Field', 'Boro Zone'),
(146, 'Brooklyn', 'Marine Park/Mill Basin', 'Boro Zone'),
(147, 'Staten Island', 'Mariners Harbor', 'Boro Zone'),
(148, 'Queens', 'Maspeth', 'Boro Zone'),
(149, 'Manhattan', 'Meatpacking/West Village West', 'Yellow Zone'),
(150, 'Bronx', 'Melrose South', 'Boro Zone'),
(151, 'Queens', 'Middle Village', 'Boro Zone'),
(152, 'Manhattan', 'Midtown Center', 'Yellow Zone'),
(153, 'Manhattan', 'Midtown East', 'Yellow Zone'),
(154, 'Manhattan', 'Midtown North', 'Yellow Zone'),
(155, 'Manhattan', 'Midtown South', 'Yellow Zone'),
(156, 'Brooklyn', 'Midwood', 'Boro Zone'),
(157, 'Manhattan', 'Morningside Heights', 'Yellow Zone'),
(158, 'Bronx', 'Morrisania/Melrose', 'Boro Zone'),
(159, 'Bronx', 'Mott Haven/Port Morris', 'Boro Zone'),
(160, 'Bronx', 'Mount Hope', 'Boro Zone'),
(161, 'Queens', 'Murray Hill', 'Boro Zone'),
(162, 'Queens', 'Murray Hill-Queens', 'Boro Zone'),
(163, 'Staten Island', 'New Dorp/Midland Beach', 'Boro Zone'),
(164, 'Queens', 'North Corona', 'Boro Zone'),
(165, 'Bronx', 'Norwood', 'Boro Zone'),
(166, 'Queens', 'Oakland Gardens', 'Boro Zone'),
(167, 'Staten Island', 'Oakwood', 'Boro Zone'),
(168, 'Brooklyn', 'Ocean Hill', 'Boro Zone'),
(169, 'Brooklyn', 'Ocean Parkway South', 'Boro Zone'),
(170, 'Queens', 'Old Astoria', 'Boro Zone'),
(171, 'Queens', 'Ozone Park', 'Boro Zone'),
(172, 'Brooklyn', 'Park Slope', 'Boro Zone'),
(173, 'Bronx', 'Parkchester', 'Boro Zone'),
(174, 'Bronx', 'Pelham Bay', 'Boro Zone'),
(175, 'Bronx', 'Pelham Bay Park', 'Boro Zone'),
(176, 'Bronx', 'Pelham Parkway', 'Boro Zone'),
(177, 'Manhattan', 'Penn Station/Madison Sq West', 'Yellow Zone'),
(178, 'Staten Island', 'Port Richmond', 'Boro Zone'),
(179, 'Brooklyn', 'Prospect-Lefferts Gardens', 'Boro Zone'),
(180, 'Brooklyn', 'Prospect Heights', 'Boro Zone'),
(181, 'Brooklyn', 'Prospect Park', 'Boro Zone'),
(182, 'Queens', 'Queens Village', 'Boro Zone'),
(183, 'Queens', 'Queensboro Hill', 'Boro Zone'),
(184, 'Queens', 'Queensbridge/Ravenswood', 'Boro Zone'),
(185, 'Manhattan', 'Randalls Island', 'Yellow Zone'),
(186, 'Brooklyn', 'Red Hook', 'Boro Zone'),
(187, 'Queens', 'Rego Park', 'Boro Zone'),
(188, 'Queens', 'Richmond Hill', 'Boro Zone'),
(189, 'Queens', 'Ridgewood', 'Boro Zone'),
(190, 'Bronx', 'Rikers Island', 'Boro Zone'),
(191, 'Bronx', 'Riverdale/North Riverdale/Fieldston', 'Boro Zone'),
(192, 'Queens', 'Rockaway Park', 'Boro Zone'),
(193, 'Manhattan', 'Roosevelt Island', 'Yellow Zone'),
(194, 'Queens', 'Rosedale', 'Boro Zone'),
(195, 'Staten Island', 'Rossville/Woodrow', 'Boro Zone'),
(196, 'Queens', 'Saint Albans', 'Boro Zone'),
(197, 'Staten Island', 'Saint George/New Brighton', 'Boro Zone'),
(198, 'Queens', 'Saint Michaels Cemetery/Woodside', 'Boro Zone'),
(199, 'Bronx', 'Schuylerville/Edgewater Park', 'Boro Zone'),
(200, 'Manhattan', 'Seaport', 'Yellow Zone'),
(201, 'Brooklyn', 'Sheepshead Bay', 'Boro Zone'),
(202, 'Manhattan', 'SoHo', 'Yellow Zone'),
(203, 'Bronx', 'Soundview/Bruckner', 'Boro Zone'),
(204, 'Bronx', 'Soundview/Castle Hill', 'Boro Zone'),
(205, 'Staten Island', 'South Beach/Dongan Hills', 'Boro Zone'),
(206, 'Queens', 'South Jamaica', 'Boro Zone'),
(207, 'Queens', 'South Ozone Park', 'Boro Zone'),
(208, 'Brooklyn', 'South Williamsburg', 'Boro Zone'),
(209, 'Queens', 'Springfield Gardens North', 'Boro Zone'),
(210, 'Queens', 'Springfield Gardens South', 'Boro Zone'),
(211, 'Bronx', 'Spuyten Duyvil/Kingsbridge', 'Boro Zone'),
(212, 'Staten Island', 'Stapleton', 'Boro Zone'),
(213, 'Brooklyn', 'Starrett City', 'Boro Zone'),
(214, 'Queens', 'Steinway', 'Boro Zone'),
(215, 'Manhattan', 'Stuy Town/Peter Cooper Village', 'Yellow Zone'),
(216, 'Brooklyn', 'Stuyvesant Heights', 'Boro Zone'),
(217, 'Queens', 'Sunnyside', 'Boro Zone'),
(218, 'Brooklyn', 'Sunset Park East', 'Boro Zone'),
(219, 'Brooklyn', 'Sunset Park West', 'Boro Zone'),
(220, 'Manhattan', 'Sutton Place/Turtle Bay North', 'Yellow Zone'),
(221, 'Manhattan', 'Times Sq/Theatre District', 'Yellow Zone'),
(222, 'Manhattan', 'TriBeCa/Civic Center', 'Yellow Zone'),
(223, 'Manhattan', 'Two Bridges/Seward Park', 'Yellow Zone'),
(224, 'Manhattan', 'UN/Turtle Bay South', 'Yellow Zone'),
(225, 'Manhattan', 'Union Sq', 'Yellow Zone'),
(226, 'Bronx', 'University Heights/Morris Heights', 'Boro Zone'),
(227, 'Manhattan', 'Upper East Side North', 'Yellow Zone'),
(228, 'Manhattan', 'Upper East Side South', 'Yellow Zone'),
(229, 'Manhattan', 'Upper West Side North', 'Yellow Zone'),
(230, 'Manhattan', 'Upper West Side South', 'Yellow Zone'),
(231, 'Bronx', 'Van Cortlandt Park', 'Boro Zone'),
(232, 'Bronx', 'Van Cortlandt Village', 'Boro Zone'),
(233, 'Bronx', 'Van Nest/Morris Park', 'Boro Zone'),
(234, 'Manhattan', 'Washington Heights North', 'Yellow Zone'),
(235, 'Manhattan', 'Washington Heights South', 'Yellow Zone'),
(236, 'Staten Island', 'West Brighton', 'Boro Zone'),
(237, 'Manhattan', 'West Chelsea/Hudson Yards', 'Yellow Zone'),
(238, 'Bronx', 'West Concourse', 'Boro Zone'),
(239, 'Bronx', 'West Farms/Bronx Zoo', 'Boro Zone'),
(240, 'Manhattan', 'West Village', 'Yellow Zone'),
(241, 'Bronx', 'Westchester Village/Unionport', 'Boro Zone'),
(242, 'Staten Island', 'Westerleigh', 'Boro Zone'),
(243, 'Queens', 'Whitestone', 'Boro Zone'),
(244, 'Queens', 'Willets Point', 'Boro Zone'),
(245, 'Bronx', 'Williamsbridge/Olinville', 'Boro Zone'),
(246, 'Brooklyn', 'Williamsburg (East Side)', 'Boro Zone'),
(247, 'Brooklyn', 'Williamsburg (North Side)', 'Boro Zone'),
(248, 'Brooklyn', 'Williamsburg (South Side)', 'Boro Zone'),
(249, 'Brooklyn', 'Windsor Terrace', 'Boro Zone'),
(250, 'Queens', 'Woodhaven', 'Boro Zone'),
(251, 'Bronx', 'Woodlawn/Wakefield', 'Boro Zone'),
(252, 'Queens', 'Woodside', 'Boro Zone'),
(253, 'Queens', 'Yorkville East', 'Boro Zone'),
(254, 'Queens', 'Yorkville West', 'Boro Zone'),
(255, 'Unknown', 'NV', 'N/A'),
(256, 'Unknown', 'Unknown', 'N/A'),
(257, 'Unknown', 'Unknown', 'N/A'),
(258, 'Unknown', 'Unknown', 'N/A'),
(259, 'Unknown', 'Unknown', 'N/A'),
(260, 'Unknown', 'Unknown', 'N/A'),
(261, 'Unknown', 'Unknown', 'N/A'),
(262, 'Unknown', 'Unknown', 'N/A'),
(263, 'Unknown', 'Unknown', 'N/A'),
(264, 'Unknown', 'Unknown', 'N/A'),
(265, 'Unknown', 'Unknown', 'N/A'),
(266, 'Unknown', 'Unknown', 'N/A'),
(267, 'Unknown', 'Unknown', 'N/A'),
(268, 'Unknown', 'Unknown', 'N/A'),
(269, 'Unknown', 'Unknown', 'N/A'),
(270, 'Unknown', 'Unknown', 'N/A'),
(271, 'Unknown', 'Unknown', 'N/A'),
(272, 'Unknown', 'Unknown', 'N/A'),
(273, 'Unknown', 'Unknown', 'N/A'),
(274, 'Unknown', 'Unknown', 'N/A'),
(275, 'Unknown', 'Unknown', 'N/A'),
(276, 'Unknown', 'Unknown', 'N/A'),
(277, 'Unknown', 'Unknown', 'N/A'),
(278, 'Unknown', 'Unknown', 'N/A'),
(279, 'Unknown', 'Unknown', 'N/A'),
(280, 'Unknown', 'Unknown', 'N/A'),
(281, 'Unknown', 'Unknown', 'N/A'),
(282, 'Unknown', 'Unknown', 'N/A'),
(283, 'Unknown', 'Unknown', 'N/A'),
(284, 'Unknown', 'Unknown', 'N/A'),
(285, 'Unknown', 'Unknown', 'N/A'),
(286, 'Unknown', 'Unknown', 'N/A'),
(287, 'Unknown', 'Unknown', 'N/A'),
(288, 'Unknown', 'Unknown', 'N/A'),
(289, 'Unknown', 'Unknown', 'N/A'),
(290, 'Unknown', 'Unknown', 'N/A'),
(291, 'Unknown', 'Unknown', 'N/A'),
(292, 'Unknown', 'Unknown', 'N/A'),
(293, 'Unknown', 'Unknown', 'N/A'),
(294, 'Unknown', 'Unknown', 'N/A'),
(295, 'Unknown', 'Unknown', 'N/A'),
(296, 'Unknown', 'Unknown', 'N/A'),
(297, 'Unknown', 'Unknown', 'N/A'),
(298, 'Unknown', 'Unknown', 'N/A'),
(299, 'Unknown', 'Unknown', 'N/A'),
(300, 'Unknown', 'Unknown', 'N/A'),
(301, 'Unknown', 'Unknown', 'N/A'),
(302, 'Unknown', 'Unknown', 'N/A'),
(303, 'Unknown', 'Unknown', 'N/A'),
(304, 'Unknown', 'Unknown', 'N/A'),
(305, 'Unknown', 'Unknown', 'N/A'),
(306, 'Unknown', 'Unknown', 'N/A'),
(307, 'Unknown', 'Unknown', 'N/A'),
(308, 'Unknown', 'Unknown', 'N/A'),
(309, 'Unknown', 'Unknown', 'N/A'),
(310, 'Unknown', 'Unknown', 'N/A'),
(311, 'Unknown', 'Unknown', 'N/A'),
(312, 'Unknown', 'Unknown', 'N/A'),
(313, 'Unknown', 'Unknown', 'N/A'),
(314, 'Unknown', 'Unknown', 'N/A'),
(315, 'Unknown', 'Unknown', 'N/A'),
(316, 'Unknown', 'Unknown', 'N/A'),
(317, 'Unknown', 'Unknown', 'N/A'),
(318, 'Unknown', 'Unknown', 'N/A'),
(319, 'Unknown', 'Unknown', 'N/A'),
(320, 'Unknown', 'Unknown', 'N/A'),
(321, 'Unknown', 'Unknown', 'N/A'),
(322, 'Unknown', 'Unknown', 'N/A'),
(323, 'Unknown', 'Unknown', 'N/A'),
(324, 'Unknown', 'Unknown', 'N/A'),
(325, 'Unknown', 'Unknown', 'N/A'),
(326, 'Unknown', 'Unknown', 'N/A'),
(327, 'Unknown', 'Unknown', 'N/A'),
(328, 'Unknown', 'Unknown', 'N/A'),
(329, 'Unknown', 'Unknown', 'N/A'),
(330, 'Unknown', 'Unknown', 'N/A'),
(331, 'Unknown', 'Unknown', 'N/A'),
(332, 'Unknown', 'Unknown', 'N/A'),
(333, 'Unknown', 'Unknown', 'N/A'),
(334, 'Unknown', 'Unknown', 'N/A'),
(335, 'Unknown', 'Unknown', 'N/A'),
(336, 'Unknown', 'Unknown', 'N/A'),
(337, 'Unknown', 'Unknown', 'N/A'),
(338, 'Unknown', 'Unknown', 'N/A'),
(339, 'Unknown', 'Unknown', 'N/A'),
(340, 'Unknown', 'Unknown', 'N/A'),
(341, 'Unknown', 'Unknown', 'N/A'),
(342, 'Unknown', 'Unknown', 'N/A'),
(343, 'Unknown', 'Unknown', 'N/A'),
(344, 'Unknown', 'Unknown', 'N/A'),
(345, 'Unknown', 'Unknown', 'N/A'),
(346, 'Unknown', 'Unknown', 'N/A'),
(347, 'Unknown', 'Unknown', 'N/A'),
(348, 'Unknown', 'Unknown', 'N/A'),
(349, 'Unknown', 'Unknown', 'N/A'),
(350, 'Unknown', 'Unknown', 'N/A'),
(351, 'Unknown', 'Unknown', 'N/A'),
(352, 'Unknown', 'Unknown', 'N/A'),
(353, 'Unknown', 'Unknown', 'N/A'),
(354, 'Unknown', 'Unknown', 'N/A'),
(355, 'Unknown', 'Unknown', 'N/A'),
(356, 'Unknown', 'Unknown', 'N/A'),
(357, 'Unknown', 'Unknown', 'N/A'),
(358, 'Unknown', 'Unknown', 'N/A'),
(359, 'Unknown', 'Unknown', 'N/A'),
(360, 'Unknown', 'Unknown', 'N/A'),
(361, 'Unknown', 'Unknown', 'N/A'),
(362, 'Unknown', 'Unknown', 'N/A'),
(363, 'Unknown', 'Unknown', 'N/A'),
(364, 'Unknown', 'Unknown', 'N/A'),
(365, 'Unknown', 'Unknown', 'N/A'),
(366, 'Unknown', 'Unknown', 'N/A'),
(367, 'Unknown', 'Unknown', 'N/A'),
(368, 'Unknown', 'Unknown', 'N/A'),
(369, 'Unknown', 'Unknown', 'N/A'),
(370, 'Unknown', 'Unknown', 'N/A'),
(371, 'Unknown', 'Unknown', 'N/A'),
(372, 'Unknown', 'Unknown', 'N/A'),
(373, 'Unknown', 'Unknown', 'N/A'),
(374, 'Unknown', 'Unknown', 'N/A'),
(375, 'Unknown', 'Unknown', 'N/A'),
(376, 'Unknown', 'Unknown', 'N/A'),
(377, 'Unknown', 'Unknown', 'N/A'),
(378, 'Unknown', 'Unknown', 'N/A'),
(379, 'Unknown', 'Unknown', 'N/A'),
(380, 'Unknown', 'Unknown', 'N/A'),
(381, 'Unknown', 'Unknown', 'N/A'),
(382, 'Unknown', 'Unknown', 'N/A'),
(383, 'Unknown', 'Unknown', 'N/A'),
(384, 'Unknown', 'Unknown', 'N/A'),
(385, 'Unknown', 'Unknown', 'N/A'),
(386, 'Unknown', 'Unknown', 'N/A'),
(387, 'Unknown', 'Unknown', 'N/A'),
(388, 'Unknown', 'Unknown', 'N/A'),
(389, 'Unknown', 'Unknown', 'N/A'),
(390, 'Unknown', 'Unknown', 'N/A'),
(391, 'Unknown', 'Unknown', 'N/A'),
(392, 'Unknown', 'Unknown', 'N/A'),
(393, 'Unknown', 'Unknown', 'N/A'),
(394, 'Unknown', 'Unknown', 'N/A'),
(395, 'Unknown', 'Unknown', 'N/A'),
(396, 'Unknown', 'Unknown', 'N/A'),
(397, 'Unknown', 'Unknown', 'N/A'),
(398, 'Unknown', 'Unknown', 'N/A'),
(399, 'Unknown', 'Unknown', 'N/A'),
(400, 'Unknown', 'Unknown', 'N/A'),
(401, 'Unknown', 'Unknown', 'N/A'),
(402, 'Unknown', 'Unknown', 'N/A'),
(403, 'Unknown', 'Unknown', 'N/A'),
(404, 'Unknown', 'Unknown', 'N/A'),
(405, 'Unknown', 'Unknown', 'N/A'),
(406, 'Unknown', 'Unknown', 'N/A'),
(407, 'Unknown', 'Unknown', 'N/A'),
(408, 'Unknown', 'Unknown', 'N/A'),
(409, 'Unknown', 'Unknown', 'N/A'),
(410, 'Unknown', 'Unknown', 'N/A'),
(411, 'Unknown', 'Unknown', 'N/A'),
(412, 'Unknown', 'Unknown', 'N/A'),
(413, 'Unknown', 'Unknown', 'N/A'),
(414, 'Unknown', 'Unknown', 'N/A'),
(415, 'Unknown', 'Unknown', 'N/A'),
(416, 'Unknown', 'Unknown', 'N/A'),
(417, 'Unknown', 'Unknown', 'N/A'),
(418, 'Unknown', 'Unknown', 'N/A'),
(419, 'Unknown', 'Unknown', 'N/A'),
(420, 'Unknown', 'Unknown', 'N/A'),
(421, 'Unknown', 'Unknown', 'N/A'),
(422, 'Unknown', 'Unknown', 'N/A'),
(423, 'Unknown', 'Unknown', 'N/A'),
(424, 'Unknown', 'Unknown', 'N/A'),
(425, 'Unknown', 'Unknown', 'N/A'),
(426, 'Unknown', 'Unknown', 'N/A'),
(427, 'Unknown', 'Unknown', 'N/A'),
(428, 'Unknown', 'Unknown', 'N/A'),
(429, 'Unknown', 'Unknown', 'N/A'),
(430, 'Unknown', 'Unknown', 'N/A'),
(431, 'Unknown', 'Unknown', 'N/A'),
(432, 'Unknown', 'Unknown', 'N/A'),
(433, 'Unknown', 'Unknown', 'N/A'),
(434, 'Unknown', 'Unknown', 'N/A'),
(435, 'Unknown', 'Unknown', 'N/A'),
(436, 'Unknown', 'Unknown', 'N/A'),
(437, 'Unknown', 'Unknown', 'N/A'),
(438, 'Unknown', 'Unknown', 'N/A'),
(439, 'Unknown', 'Unknown', 'N/A'),
(440, 'Unknown', 'Unknown', 'N/A'),
(441, 'Unknown', 'Unknown', 'N/A'),
(442, 'Unknown', 'Unknown', 'N/A'),
(443, 'Unknown', 'Unknown', 'N/A'),
(444, 'Unknown', 'Unknown', 'N/A'),
(445, 'Unknown', 'Unknown', 'N/A'),
(446, 'Unknown', 'Unknown', 'N/A'),
(447, 'Unknown', 'Unknown', 'N/A'),
(448, 'Unknown', 'Unknown', 'N/A'),
(449, 'Unknown', 'Unknown', 'N/A'),
(450, 'Unknown', 'Unknown', 'N/A'),
(451, 'Unknown', 'Unknown', 'N/A'),
(452, 'Unknown', 'Unknown', 'N/A'),
(453, 'Unknown', 'Unknown', 'N/A'),
(454, 'Unknown', 'Unknown', 'N/A'),
(455, 'Unknown', 'Unknown', 'N/A'),
(456, 'Unknown', 'Unknown', 'N/A'),
(457, 'Unknown', 'Unknown', 'N/A'),
(458, 'Unknown', 'Unknown', 'N/A'),
(459, 'Unknown', 'Unknown', 'N/A'),
(460, 'Unknown', 'Unknown', 'N/A'),
(461, 'Unknown', 'Unknown', 'N/A'),
(462, 'Unknown', 'Unknown', 'N/A'),
(463, 'Unknown', 'Unknown', 'N/A'),
(464, 'Unknown', 'Unknown', 'N/A'),
(465, 'Unknown', 'Unknown', 'N/A'),
(466, 'Unknown', 'Unknown', 'N/A'),
(467, 'Unknown', 'Unknown', 'N/A'),
(468, 'Unknown', 'Unknown', 'N/A'),
(469, 'Unknown', 'Unknown', 'N/A'),
(470, 'Unknown', 'Unknown', 'N/A'),
(471, 'Unknown', 'Unknown', 'N/A'),
(472, 'Unknown', 'Unknown', 'N/A'),
(473, 'Unknown', 'Unknown', 'N/A'),
(474, 'Unknown', 'Unknown', 'N/A'),
(475, 'Unknown', 'Unknown', 'N/A'),
(476, 'Unknown', 'Unknown', 'N/A'),
(477, 'Unknown', 'Unknown', 'N/A'),
(478, 'Unknown', 'Unknown', 'N/A'),
(479, 'Unknown', 'Unknown', 'N/A'),
(480, 'Unknown', 'Unknown', 'N/A'),
(481, 'Unknown', 'Unknown', 'N/A'),
(482, 'Unknown', 'Unknown', 'N/A'),
(483, 'Unknown', 'Unknown', 'N/A'),
(484, 'Unknown', 'Unknown', 'N/A'),
(485, 'Unknown', 'Unknown', 'N/A'),
(486, 'Unknown', 'Unknown', 'N/A'),
(487, 'Unknown', 'Unknown', 'N/A'),
(488, 'Unknown', 'Unknown', 'N/A'),
(489, 'Unknown', 'Unknown', 'N/A'),
(490, 'Unknown', 'Unknown', 'N/A'),
(491, 'Unknown', 'Unknown', 'N/A'),
(492, 'Unknown', 'Unknown', 'N/A'),
(493, 'Unknown', 'Unknown', 'N/A'),
(494, 'Unknown', 'Unknown', 'N/A'),
(495, 'Unknown', 'Unknown', 'N/A'),
(496, 'Unknown', 'Unknown', 'N/A'),
(497, 'Unknown', 'Unknown', 'N/A'),
(498, 'Unknown', 'Unknown', 'N/A'),
(499, 'Unknown', 'Unknown', 'N/A'),
(500, 'Unknown', 'Unknown', 'N/A')
ON CONFLICT (location_id) DO NOTHING;


